apiVersion: v1
kind: Secret
metadata:
  name: order
type: Opaque
data:
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdzcWwtcG9zdGdyZXNxbC5zaG9wOjU0MzIvZGJfb3JkZXI=
  DB_USER: dV9vcmRlcg==
  DB_PASSWORD: b3JkZXI=
  CUSTOMER_SERVICE_URL: aHR0cDovL2N1c3RvbWVyLXNlcnZpY2Uuc2hvcDo4MDgxL2N1c3RvbWVy
