apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: lkusmierczyk/order-service:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8082
          env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: order
                key: DB_URL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: order
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order
                key: DB_PASSWORD
          - name: CUSTOMER_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: order
                key: CUSTOMER_SERVICE_URL
