apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: lkusmierczyk/customer-service:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: customer
                key: DB_URL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: customer
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: customer
                key: DB_PASSWORD
